### PR TITLE
Require dependencydoctrine common

### PR DESCRIPTION
**Pull request by rdss-dkontsevoi**
in src/FixtureManager/FixtureManager.php:222 the \Doctrine\Common\Persistence\ObjectManager namespace is used as prod requirement (building via factory...)

### CODE REVIEW

**Comment by DavidBadura** [comment]
Hello @rdss-dkontsevoi, thank you for the contribution.

Doctrine ORM or Doctrine MongoDB is an optional dependency. Instance of checks don't require that the class exists, so we don't need require it. If you want to use Doctrine, you need require it in you projects.

**Comment by rdss-dkontsevoi** [comment]
> Hello @rdss-dkontsevoi, thank you for the contribution.
> 
> Doctrine ORM or Doctrine MongoDB is an optional dependency. Instance of checks don't require that the class exists, so we don't need require it. If you want to use Doctrine, you need require it in your projects.

Hello David,

In future i plan to use your package for newer version of doctrine/common:v3.0. My Console application crashed in case of using doctrine/common:v2.0 (**now required as dev**) -- In this case if you think so, you can ignore this pull request. 

I'll create an other pull request for using **doctrine/common:v3.0** and try to keep this dependency as dev.
The namespace will change from \Doctrine\Common\Persistence\ObjectManager to Doctrine\Persistence\ObjectManager.

Could you please create later a new breaking change release version for us? 

Thanks,
Dimitri

**Comment by DavidBadura** [comment]
Yes, can do this. I would then also want to pull up a few minimum versions. Which PHP version are you using?

**Comment by rdss-dkontsevoi** [comment]
> Yes, can do this. I would then also want to pull up a few minimum versions. Which PHP version are you using?

We are using PHP 7.4. Thanks for such as fast reply. But i don't know how to handle it with this pull request. 
I understand your argument, that that is a optional dependency. 
But if i use newer doctrine versions, then composer won't tell us about incompatibility (because it marked as a dev)

**Comment by rdss-dkontsevoi** [comment]
closed because of duplicate. more in https://github.com/DavidBadura/Fixtures/pull/21

**Pull request closed without merging**
