### PR TITLE
using doctrine common v3

### PR DESCRIPTION
**Pull request by rdss-dkontsevoi**
works for me locally with: 

beberlei/doctrineextensions v1.3.0 
doctrine/annotations    1.13.2       
doctrine/cache   1.12.1 
doctrine/collections   1.6.8 
**doctrine/common    3.1.2** 
doctrine/dbal  2.13.4  
doctrine/deprecations  v0.5.3
doctrine/event-manager 1.1.1 
doctrine/inflector   2.0.4   
doctrine/instantiator  1.4.0
doctrine/lexer   1.2.1  
doctrine/orm  2.9.5
doctrine/persistence   2.2.2 

i checked all namespaces of doctrine/common . But please check anything else functional (unit tests was green..).

### CODE REVIEW

**Comment by DavidBadura** [comment]
@rdss-dkontsevoi can you try the master branch? if it works, i can release a new version

**Comment by rdss-dkontsevoi** [comment]
> @rdss-dkontsevoi can you try the master branch? if it works, i can release a new version

ok i can discard all my changes to composer.json, but https://github.com/DavidBadura/Fixtures/pull/21/files#diff-c69d3671bb5a2dc531a3518471d61a8949428db96c86c7c9bcaa83d56e42c1efR222 we need here a type of version switching for doctrine/common < 3 , its with common in namespacing, for common >= 3 ist without common

**Comment by rdss-dkontsevoi** [comment]
rebase done & implemented version switch. i'll test it tomorrow again and give you feedback.
If it's finally works. You can do a non bc release :)

thanks

**Comment by rdss-dkontsevoi** [comment]
@DavidBadura thx for support. its working for me. Could you merge it and make a new feature release?

**Comment by DavidBadura** [comment]
@rdss-dkontsevoi this check is not necessary. With doctrine/persistence it has an BC Layer already. So you don't need check which version you have:

https://github.com/doctrine/persistence/blob/1.3.x/lib/Doctrine/Common/Persistence/ObjectManager.php

Do you try the master branch without you changes? It should already work, for doctrine/common 2 and 3.

**Pull request closed without merging**
